version: '3.8'

services:
  db:
    image: postgres:17-alpine
    restart: always
    env_file: ".env"
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - dbnet

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    links:
      - "db:db"
    networks:
      - dbnet
    depends_on:
      - db

volumes:
  pg_data:

networks:
  dbnet:
    driver: bridge
