version: '3.8'

services:
  db:
    image: postgres:17-alpine
    restart: always
    env_file: ".env"
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
